title: Lily on the rails
author:
  name: Lily
  email: lilyontherails@gmail.com
  
description: > 
  In which Lily tries to blog through GitHub Pages

# theme: minima
remote_theme: jekyll/minima

plugins: 
  - jekyll-spaceship

header_pages:
  - about.md

minima:
  skin: classic

markdown: kramdown

kramdown:
  parse_block_html: true
